name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: ["jamesgober"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 1.2.3
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      render: shell   # syntax-highlights as code
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - macOS
        - Linux
      multiple: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues
          required: true